site_name: Documentation
site_url: https://documentation.secondstage.io
extra_css:
  - stylesheets/extra.css?v=2
extra_javascript:
  - javascripts/extra.js
theme:
  name: material
  logo: assets/2s-logo.png
  favicon: assets/favicon.png
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  palette:
    # 1. Automatic (System) Preference
    # Falls back to white/pink if system preference is unknown
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: white 
      accent: pink

    # 2. Light Mode
    # "primary: white" gives you the clean, white header (Stripe-style)
    # The CSS we added earlier will color the Logo and Active Links pink.
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: white
      accent: pink

    # 3. Dark Mode
    # "primary: black" ensures the header matches the dark background
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: black
      accent: pink

      
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/secondstage/
  homepage: https://documentation.secondstage.io
  generator: false
  
# Extensions 
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      title: Table of contents
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search

copyright: |
  &copy; 2025 <a href="https://secondstage.io"  target="_blank" rel="noopener">Second Stage GmbH</a>

# Page tree 
nav:
  - Home: index.md
  - TRACKS Overview:
    - Overview: overview/overview.md
    - Functionality: overview/functionality.md
    - Integration: overview/integration.md
    - Ad Ops Guide: overview/adopshelper.md 
  - Platform Integration: 
    - Overview: platform/overview.md
    - Media Platform Access: platform/mediachannels.md
    - Landing Page Integration: platform/landingpages.md
    - Steamworks Integration: platform/steamworks.md
    - Custom Domains: platform/domains.md
    - Postbacks: platform/postbacks.md
    - Tracking Links: platform/trackinglinks.md
  - Attribution Integration: 
    - Overview: attribution/overview.md
    - Cloud Setup: attribution/cloud.md
    - TRACKS Measurement API: attribution/measurementapi.md
    - Telemetry Setup: attribution/telemetry.md
    - GDPR API: attribution/gdprapi.md
  - Knowledge Base:
    - Overview: support/overview.md
    - Attribution Tracking: support/attribution.md
    - Marketing Analytics: support/marketinganalytics.md
    - Data Collection: support/datacollection.md
    - Data Handling & Security: support/datasecurity.md
    - Further Reading: support/furtherreading.md
  - Glossary: glossary.md
  - Changelog: changelog.md


